plugin-prefix: "&a[MyzticCore]"
debug-mode: false

sql-database-details:
  use: true
  host: "hostname"
  user: "user"
  password: "pwd"
  database: "dbname"
  port: 0000
  driver: "mysql"
  tls-version: ""
  use-SSL: false